version: "3"

services:
  db:
    image: postgres:15.1
    volumes:
      - ./TDB.Generate/init:/docker-entrypoint-initdb.d
    environment:
      LANG: C.UTF-8
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
